"""Seed restaurant data and DB seeding for Fork·Fate."""
import logging
from core import db
from models import Restaurant


SEED = [
    {"name": "Olive & Ember", "cuisine": "Italian", "price": "$$", "rating": 4.7, "distance": 0.8, "sponsored": True,
     "description": "Wood-fired pizzas and hand-rolled pasta in a warm, candle-lit room.", "address": "12 Maple Ave",
     "image": "https://images.unsplash.com/photo-1564759296729-771e78c26df7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NTYxODd8MHwxfHNlYXJjaHw0fHxnb3VybWV0JTIwcmVzdGF1cmFudCUyMGZvb2QlMjBkaXNoJTIwcGxhdGVkfGVufDB8fHx8MTc4MzIwNDE1Nnww&ixlib=rb-4.1.0&q=85"},
    {"name": "The Copper Grill", "cuisine": "Steakhouse", "price": "$$$", "rating": 4.8, "distance": 2.3,
     "description": "Dry-aged cuts and bold sauces plated tableside.", "address": "88 Harbor St",
     "image": "https://images.unsplash.com/photo-1663530761401-15eefb544889?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NTYxODd8MHwxfHNlYXJjaHwyfHxnb3VybWV0JTIwcmVzdGF1cmFudCUyMGZvb2QlMjBkaXNoJTIwcGxhdGVkfGVufDB8fHx8MTc4MzIwNDE1Nnww&ixlib=rb-4.1.0&q=85"},
    {"name": "Nori House", "cuisine": "Japanese", "price": "$$", "rating": 4.6, "distance": 1.5,
     "description": "Omakase sushi and salmon donburi from a tiny counter kitchen.", "address": "5 Lantern Ln",
     "image": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NTYxODd8MHwxfHNlYXJjaHwxfHxnb3VybWV0JTIwcmVzdGF1cmFudCUyMGZvb2QlMjBkaXNoJTIwcGxhdGVkfGVufDB8fHx8MTc4MzIwNDE1Nnww&ixlib=rb-4.1.0&q=85"},
    {"name": "Barrel & Bean", "cuisine": "Cafe", "price": "$", "rating": 4.4, "distance": 0.4,
     "description": "Slow-brew coffee, sourdough toasts and all-day brunch.", "address": "3 Corner Rd",
     "image": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzV8MHwxfHNlYXJjaHwxfHxyZXN0YXVyYW50JTIwaW50ZXJpb3IlMjBhbWJpYW5jZXxlbnwwfHx8fDE3ODMyMDQxNTZ8MA&ixlib=rb-4.1.0&q=85"},
    {"name": "Casa Verde", "cuisine": "Mexican", "price": "$", "rating": 4.5, "distance": 1.1,
     "description": "Street tacos, smoky salsas and fresh lime margaritas.", "address": "44 Sol Blvd",
     "image": "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzV8MHwxfHNlYXJjaHwzfHxyZXN0YXVyYW50JTIwaW50ZXJpb3IlMjBhbWJpYW5jZXxlbnwwfHx8fDE3ODMyMDQxNTZ8MA&ixlib=rb-4.1.0&q=85"},
    {"name": "Saffron Route", "cuisine": "Indian", "price": "$$", "rating": 4.7, "distance": 2.9,
     "description": "Slow-cooked curries, tandoor breads and fragrant biryanis.", "address": "21 Spice Way",
     "image": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MHx8fGVufDB8fHx8&ixlib=rb-4.1.0&q=85"},
    {"name": "Golden Wok", "cuisine": "Chinese", "price": "$", "rating": 4.3, "distance": 1.8,
     "description": "Hand-pulled noodles and blistered dumplings from the wok.", "address": "9 Jade St",
     "image": "https://images.unsplash.com/photo-1552611052-33e04de081de?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MHx8fGVufDB8fHx8&ixlib=rb-4.1.0&q=85"},
    {"name": "The Green Fork", "cuisine": "Vegan", "price": "$$", "rating": 4.6, "distance": 0.9,
     "description": "Plant-forward bowls, house ferments and cold-pressed juices.", "address": "17 Garden Pl",
     "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MHx8fGVufDB8fHx8&ixlib=rb-4.1.0&q=85"},
    {"name": "Harborline", "cuisine": "Seafood", "price": "$$$", "rating": 4.9, "distance": 3.4, "sponsored": True,
     "description": "Daily catch, chilled towers and coastal white wines.", "address": "1 Pier View",
     "image": "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MHx8fGVufDB8fHx8&ixlib=rb-4.1.0&q=85"},
    {"name": "Smoke & Stack", "cuisine": "Burgers", "price": "$", "rating": 4.4, "distance": 1.3,
     "description": "Smashed patties, house pickles and thick-cut fries.", "address": "30 Grill Rd",
     "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MHx8fGVufDB8fHx8&ixlib=rb-4.1.0&q=85"},
    {"name": "Petit Marais", "cuisine": "French", "price": "$$$", "rating": 4.8, "distance": 2.0,
     "description": "Bistro classics, buttery pastries and natural wine.", "address": "7 Rue Belle",
     "image": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MHx8fGVufDB8fHx8&ixlib=rb-4.1.0&q=85"},
    {"name": "Mezze Lane", "cuisine": "Mediterranean", "price": "$$", "rating": 4.6, "distance": 1.6,
     "description": "Charred flatbreads, dips and slow-roasted lamb.", "address": "58 Cedar Ct",
     "image": "https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MHx8fGVufDB8fHx8&ixlib=rb-4.1.0&q=85"},
    {"name": "Bangkok Orchid", "cuisine": "Thai", "price": "$$", "rating": 4.7, "distance": 4.2,
     "description": "Fiery green curry, pad thai and mango sticky rice.", "address": "62 Lotus St",
     "image": "https://images.unsplash.com/photo-1559314809-0d155014e29e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Seoul Kitchen", "cuisine": "Korean", "price": "$$", "rating": 4.6, "distance": 6.5,
     "description": "Sizzling bibimbap, tabletop BBQ and kimchi stews.", "address": "9 Hangang Rd",
     "image": "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Slice District", "cuisine": "Pizza", "price": "$", "rating": 4.5, "distance": 2.7,
     "description": "Blistered Neapolitan pies from a 900° oven.", "address": "14 Dough Ave",
     "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Diner on 5th", "cuisine": "American", "price": "$", "rating": 4.3, "distance": 3.1,
     "description": "All-day pancakes, milkshakes and bottomless coffee.", "address": "5th & Main",
     "image": "https://images.unsplash.com/photo-1550547660-d9450f859349?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Pho Saigon", "cuisine": "Vietnamese", "price": "$", "rating": 4.6, "distance": 7.8,
     "description": "Steaming pho, crisp banh mi and iced coffee.", "address": "23 Mekong Ln",
     "image": "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Ember & Oak BBQ", "cuisine": "BBQ", "price": "$$", "rating": 4.8, "distance": 12.4, "sponsored": True,
     "description": "Low-and-slow brisket, ribs and burnt ends.", "address": "40 Smokehouse Rd",
     "image": "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Santorini Blue", "cuisine": "Greek", "price": "$$", "rating": 4.7, "distance": 9.3,
     "description": "Grilled octopus, souvlaki and honey-drizzled baklava.", "address": "11 Aegean Way",
     "image": "https://images.unsplash.com/photo-1600335895229-6e75511892c8?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Tokyo Ramen Bar", "cuisine": "Japanese", "price": "$", "rating": 4.7, "distance": 5.6,
     "description": "Rich tonkotsu broth and springy hand-cut noodles.", "address": "8 Shinjuku St",
     "image": "https://images.unsplash.com/photo-1557872943-16a5ac26437e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "El Pastor", "cuisine": "Mexican", "price": "$$", "rating": 4.6, "distance": 15.2,
     "description": "Al pastor off the trompo, elote and mezcal flights.", "address": "77 Agave Blvd",
     "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Oyster Club", "cuisine": "Seafood", "price": "$$$", "rating": 4.9, "distance": 22.0,
     "description": "Raw bar, lobster rolls and crisp muscadet.", "address": "2 Wharf Rd",
     "image": "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Verde Cantina", "cuisine": "Vegan", "price": "$", "rating": 4.4, "distance": 34.5,
     "description": "Jackfruit tacos, cashew queso and kombucha on tap.", "address": "90 Fern Hill",
     "image": "https://images.unsplash.com/photo-1540914124281-342587941389?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Buffalo Junction", "cuisine": "Chicken Wings", "price": "$$", "rating": 4.6, "distance": 3.2, "sponsored": True,
     "description": "Crispy buffalo wings, dry rubs and blue-cheese dip.", "address": "48 Coop Ave",
     "image": "https://images.unsplash.com/photo-1608039755401-742074f0548d?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Cluck & Fire", "cuisine": "Chicken Wings", "price": "$", "rating": 4.5, "distance": 6.7,
     "description": "Nashville-hot wings and loaded fries.", "address": "12 Flame St",
     "image": "https://images.unsplash.com/photo-1527477396000-e27163b481c2?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Corner Deli & Co", "cuisine": "Deli", "price": "$", "rating": 4.6, "distance": 1.9, "sponsored": True,
     "description": "Stacked pastrami subs, house pickles and fresh bagels.", "address": "33 Market St",
     "image": "https://images.unsplash.com/photo-1509722747041-616f39b57569?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Rye & Slice", "cuisine": "Deli", "price": "$$", "rating": 4.5, "distance": 4.4,
     "description": "Classic reubens, matzo ball soup and egg creams.", "address": "7 Rye Ln",
     "image": "https://images.unsplash.com/photo-1553909489-cd47e0ef937f?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Sunrise Diner", "cuisine": "Breakfast", "price": "$", "rating": 4.6, "distance": 1.7, "sponsored": True,
     "description": "Fluffy pancakes, skillets and bottomless coffee all morning.", "address": "6 Dawn St",
     "image": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Morning Table", "cuisine": "Breakfast", "price": "$$", "rating": 4.7, "distance": 5.3,
     "description": "Avocado toast, shakshuka and fresh-pressed juices.", "address": "22 Brunch Ave",
     "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Scoops & Swirls", "cuisine": "Ice Cream", "price": "$", "rating": 4.8, "distance": 1.5, "category": "desserts", "sponsored": True,
     "description": "Small-batch gelato, waffle cones and sundae bar.", "address": "5 Sugar Ln",
     "image": "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Frostbite Creamery", "cuisine": "Ice Cream", "price": "$", "rating": 4.6, "distance": 4.7, "category": "desserts",
     "description": "Rolled ice cream, milkshakes and vegan scoops.", "address": "40 Frost St",
     "image": "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Sweet Tooth Co", "cuisine": "Candy Shops", "price": "$", "rating": 4.7, "distance": 2.2, "category": "desserts", "sponsored": True,
     "description": "Bulk candy walls, chocolate truffles and nostalgic sweets.", "address": "18 Confection Ct",
     "image": "https://images.unsplash.com/photo-1499195333224-3ce974eecb47?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Candy Jar", "cuisine": "Candy Shops", "price": "$", "rating": 4.5, "distance": 6.9, "category": "desserts",
     "description": "Handmade fudge, taffy and old-fashioned lollipops.", "address": "3 Toffee Way",
     "image": "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Flour & Butter Bakery", "cuisine": "Bakery", "price": "$$", "rating": 4.8, "distance": 2.0, "category": "desserts", "sponsored": True,
     "description": "Croissants, layer cakes and fresh-from-the-oven pastries.", "address": "11 Baker St",
     "image": "https://images.unsplash.com/photo-1509440159596-0249088772ff?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Rise & Crumb", "cuisine": "Bakery", "price": "$", "rating": 4.6, "distance": 5.8, "category": "desserts",
     "description": "Sourdough loaves, cookies and cinnamon rolls.", "address": "27 Dough Ave",
     "image": "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Berry Swirl", "cuisine": "Frozen Yogurt", "price": "$", "rating": 4.5, "distance": 3.4, "category": "desserts",
     "description": "Self-serve froyo with 40 toppings and fresh fruit.", "address": "9 Tart Ln",
     "image": "https://images.unsplash.com/photo-1488900128323-21503983a07e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Chill Yo", "cuisine": "Frozen Yogurt", "price": "$", "rating": 4.4, "distance": 7.1, "category": "desserts",
     "description": "Tart froyo swirls, boba toppings and sorbet.", "address": "52 Swirl Rd",
     "image": "https://images.unsplash.com/photo-1560008581-09826d1de69e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Cloud Nine Coffee", "cuisine": "Coffee", "price": "$", "rating": 4.7, "distance": 0.6, "category": "drinks", "sponsored": True,
     "description": "Single-origin pour-overs, flat whites and flaky croissants.", "address": "6 Bean St",
     "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Roast & Co", "cuisine": "Coffee", "price": "$$", "rating": 4.6, "distance": 2.1, "category": "drinks",
     "description": "Small-batch roasters with nitro cold brew on tap.", "address": "19 Ember Ave",
     "image": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Pearl & Pour", "cuisine": "Boba Tea", "price": "$", "rating": 4.8, "distance": 1.4, "category": "drinks", "sponsored": True,
     "description": "Brown-sugar boba, fruit teas and cheese foam.", "address": "8 Tapioca Ln",
     "image": "https://images.unsplash.com/photo-1558857563-b371033873b8?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Boba Lab", "cuisine": "Boba Tea", "price": "$", "rating": 4.5, "distance": 3.7, "category": "drinks",
     "description": "Build-your-own milk teas with popping pearls.", "address": "27 Pearl Rd",
     "image": "https://images.unsplash.com/photo-1525803377221-4f6ccf6f0d1a?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Sip Society", "cuisine": "Smoothie", "price": "$$", "rating": 4.6, "distance": 2.8, "category": "drinks",
     "description": "Cold-pressed juices and protein-packed smoothie bowls.", "address": "51 Blend Blvd",
     "image": "https://images.unsplash.com/photo-1502741224143-90386d7f8c82?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Green Blend", "cuisine": "Smoothie", "price": "$", "rating": 4.4, "distance": 5.9, "category": "drinks",
     "description": "Acai bowls, green smoothies and chia parfaits.", "address": "3 Kale Ct",
     "image": "https://images.unsplash.com/photo-1610970881699-44a5587cabec?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Daily Grind", "cuisine": "Coffee", "price": "$", "rating": 4.5, "distance": 8.2, "category": "drinks",
     "description": "Neighborhood espresso bar with house oat milk.", "address": "72 Roast Row",
     "image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Tapioca Town", "cuisine": "Boba Tea", "price": "$", "rating": 4.3, "distance": 11.5, "category": "drinks",
     "description": "Classic milk teas, taro slushies and mochi bites.", "address": "14 Chew St",
     "image": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Tap House", "cuisine": "Beer", "price": "$$", "rating": 4.7, "distance": 1.2, "category": "bars", "sponsored": True,
     "description": "40 rotating craft taps and wood-fired pretzels.", "address": "5 Hops Ave",
     "image": "https://images.unsplash.com/photo-1436076863939-06870fe779c2?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Barrel & Bourbon", "cuisine": "Whiskey", "price": "$$$", "rating": 4.8, "distance": 2.6, "category": "bars",
     "description": "200-bottle whiskey library and craft old fashioneds.", "address": "88 Rye Rd",
     "image": "https://images.unsplash.com/photo-1569924995012-c4c706bfcd51?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "O'Malley's", "cuisine": "Irish Bar", "price": "$$", "rating": 4.6, "distance": 3.9, "category": "bars", "sponsored": True,
     "description": "Perfectly poured stout, live trad music and pub grub.", "address": "17 Shamrock St",
     "image": "https://images.unsplash.com/photo-1514933651103-005eec06c04b?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The End Zone", "cuisine": "Sports Bar", "price": "$$", "rating": 4.4, "distance": 5.1, "category": "bars",
     "description": "30 screens, wings and ice-cold buckets on game day.", "address": "42 Stadium Way",
     "image": "https://images.unsplash.com/photo-1543007630-9710e4a00a20?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Agave Nights", "cuisine": "Margaritas", "price": "$$", "rating": 4.7, "distance": 4.3, "category": "bars",
     "description": "Frozen and fresh-lime margaritas with 60 tequilas.", "address": "9 Lime Blvd",
     "image": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Tiki Lagoon", "cuisine": "Tiki", "price": "$$$", "rating": 4.6, "distance": 7.2, "category": "bars",
     "description": "Flaming mai tais and rum flights under bamboo.", "address": "3 Palm Cove",
     "image": "https://images.unsplash.com/photo-1470337458703-46ad1756a187?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Liquor Room", "cuisine": "Liquor", "price": "$$$", "rating": 4.5, "distance": 6.4, "category": "bars",
     "description": "Speakeasy cocktails and a top-shelf back bar.", "address": "21 Vault Ln",
     "image": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Copper Still", "cuisine": "Spirits", "price": "$$$", "rating": 4.7, "distance": 8.8, "category": "bars",
     "description": "Small-batch spirits tastings and craft cocktails.", "address": "60 Distillery Rd",
     "image": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Last Call", "cuisine": "Bars", "price": "$", "rating": 4.3, "distance": 9.5, "category": "bars",
     "description": "Neighborhood dive with cheap drafts and a jukebox.", "address": "1 Corner Tap",
     "image": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Rack 'Em Billiards", "cuisine": "Pool", "price": "$$", "rating": 4.5, "distance": 3.3, "category": "bars", "sponsored": True,
     "description": "A dozen pro pool tables, craft beer and late-night eats.", "address": "24 Cue St",
     "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Bullseye Tavern", "cuisine": "Darts", "price": "$", "rating": 4.4, "distance": 4.8, "category": "bars",
     "description": "Electronic and steel-tip dart leagues nightly.", "address": "18 Oche Rd",
     "image": "https://images.unsplash.com/photo-1595265677860-9a3ca5c8e5c0?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Sand Bar", "cuisine": "Volleyball", "price": "$$", "rating": 4.6, "distance": 7.9, "category": "bars",
     "description": "Sand volleyball courts, frozen drinks and beach vibes.", "address": "9 Dune Way",
     "image": "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Encore", "cuisine": "Music", "price": "$$", "rating": 4.7, "distance": 5.5, "category": "bars", "sponsored": True,
     "description": "Live bands every night and a stacked cocktail list.", "address": "31 Stage Ln",
     "image": "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Dill Dinkers", "cuisine": "Pickle Ball", "price": "$$", "rating": 4.6, "distance": 6.1, "category": "bars",
     "description": "Indoor pickleball courts with a full bar and food.", "address": "12 Paddle Ct",
     "image": "https://images.unsplash.com/photo-1687204209659-3bded6aecd79?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Player One", "cuisine": "Games", "price": "$", "rating": 4.5, "distance": 8.4, "category": "bars",
     "description": "Retro arcade barcade with pinball and craft brews.", "address": "1 Arcade Alley",
     "image": "https://images.unsplash.com/photo-1511512578047-dfb367046420?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Strike & Spare", "cuisine": "Bowling", "price": "$$", "rating": 4.5, "distance": 10.2, "category": "bars",
     "description": "Boutique bowling lanes, cocktails and shareable plates.", "address": "77 Lane Ave",
     "image": "https://images.unsplash.com/photo-1538511246516-427062a4e9e6?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Wine Cellar", "cuisine": "Wine", "price": "$$$", "rating": 4.8, "distance": 2.4, "category": "bars", "sponsored": True,
     "description": "300 labels by the glass and a candle-lit tasting room.", "address": "14 Vine St",
     "image": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Shaker & Spoon", "cuisine": "Cocktails", "price": "$$$", "rating": 4.7, "distance": 3.6, "category": "bars",
     "description": "Craft cocktails and seasonal infusions by master mixologists.", "address": "29 Bitters Blvd",
     "image": "https://images.unsplash.com/photo-1470337458703-46ad1756a187?crop=entropy&cs=srgb&fm=jpg&q=85"},

    # --- Shops ---
    {"name": "Rustic Relics", "cuisine": "Antiques", "price": "$$", "rating": 4.7, "distance": 1.4, "category": "shops", "sponsored": True,
     "description": "Vintage furniture, mirrors and one-of-a-kind curios.", "address": "14 Heritage Ln",
     "image": "https://images.unsplash.com/photo-1758380742318-4074cce52ec4?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Curio Cabinet", "cuisine": "Antiques", "price": "$$", "rating": 4.5, "distance": 5.2, "category": "shops",
     "description": "Two floors of estate finds, glassware and old maps.", "address": "3 Attic Ave",
     "image": "https://images.unsplash.com/photo-1742818379540-b9ae978cfaad?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Second Life Thrift", "cuisine": "Thrift Store", "price": "$", "rating": 4.6, "distance": 2.1, "category": "shops", "sponsored": True,
     "description": "Racks of pre-loved fashion, books and household treasures.", "address": "88 Recycle Rd",
     "image": "https://images.unsplash.com/photo-1521335629791-ce4aec67dd15?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Fern & Feather Vintage", "cuisine": "Vintage", "price": "$$", "rating": 4.7, "distance": 3.8, "category": "shops",
     "description": "Curated 70s and 80s threads, boots and denim.", "address": "27 Retro St",
     "image": "https://images.unsplash.com/photo-1615420733091-6b320329987b?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Consignment Corner", "cuisine": "Consignment", "price": "$$", "rating": 4.5, "distance": 4.4, "category": "shops",
     "description": "Gently-used designer bags, shoes and coats.", "address": "9 Resale Row",
     "image": "https://images.unsplash.com/photo-1637228393246-c38a4b3d2011?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Groove Vinyl", "cuisine": "Record Store", "price": "$$", "rating": 4.8, "distance": 1.9, "category": "shops", "sponsored": True,
     "description": "Crates of new and used vinyl across every genre.", "address": "12 Wax Way",
     "image": "https://images.unsplash.com/photo-1530288782965-fbad40327074?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Spin City Records", "cuisine": "Record Store", "price": "$", "rating": 4.6, "distance": 6.3, "category": "shops",
     "description": "Rare pressings, turntables and listening booths.", "address": "44 Groove Blvd",
     "image": "https://images.unsplash.com/photo-1488841714725-bb4c32d1ac94?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Reading Nook", "cuisine": "Bookstore", "price": "$$", "rating": 4.8, "distance": 1.2, "category": "shops", "sponsored": True,
     "description": "Independent bookshop with a cozy cafe and reading chairs.", "address": "5 Chapter Ln",
     "image": "https://images.unsplash.com/photo-1518373714866-3f1478910cc0?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Dusty Pages Books", "cuisine": "Bookstore", "price": "$", "rating": 4.7, "distance": 7.5, "category": "shops",
     "description": "Floor-to-ceiling used books and first editions.", "address": "31 Spine St",
     "image": "https://images.unsplash.com/photo-1573592371950-348a8f1d9f38?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Harvest Green Market", "cuisine": "Farmers Market", "price": "$", "rating": 4.9, "distance": 2.6, "category": "shops", "sponsored": True,
     "description": "Local produce, fresh flowers and artisan goods every weekend.", "address": "1 Orchard Sq",
     "image": "https://images.unsplash.com/photo-1687199129802-3e4cc27baac0?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Town Square Farmers Market", "cuisine": "Farmers Market", "price": "$", "rating": 4.7, "distance": 5.9, "category": "shops",
     "description": "Farm-fresh veggies, honey, baked goods and cheese.", "address": "20 Meadow Rd",
     "image": "https://images.unsplash.com/photo-1616362406547-1c556ceb4d80?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Weekend Flea", "cuisine": "Flea Market", "price": "$", "rating": 4.5, "distance": 4.1, "category": "shops",
     "description": "Dozens of stalls of oddities, crafts and collectibles.", "address": "60 Bargain Ave",
     "image": "https://images.unsplash.com/photo-1663366936874-e0cf8ad40d81?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Flea & Found", "cuisine": "Flea Market", "price": "$", "rating": 4.4, "distance": 8.8, "category": "shops",
     "description": "Open-air market with tools, records and knick-knacks.", "address": "3 Swap Ln",
     "image": "https://images.unsplash.com/photo-1685875018101-a3e87efdb1d1?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Panel Zero Comics", "cuisine": "Comic Store", "price": "$$", "rating": 4.7, "distance": 3.3, "category": "shops", "sponsored": True,
     "description": "New issues, graphic novels and back-issue long boxes.", "address": "8 Hero Ct",
     "image": "https://images.unsplash.com/photo-1749999589464-4810447142bb?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Trading Post", "cuisine": "Trading Cards", "price": "$$", "rating": 4.6, "distance": 5.7, "category": "shops",
     "description": "Sports and TCG singles, booster boxes and grading.", "address": "17 Deck St",
     "image": "https://images.unsplash.com/photo-1698177077434-17523aea69c6?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Wonder Toys", "cuisine": "Toy Store", "price": "$$", "rating": 4.8, "distance": 2.4, "category": "shops", "sponsored": True,
     "description": "Wall-to-wall toys, puzzles and games for all ages.", "address": "10 Play Pl",
     "image": "https://images.unsplash.com/photo-1761207300250-a71b2ff68b99?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Brick & Block", "cuisine": "LEGO Store", "price": "$$", "rating": 4.7, "distance": 6.1, "category": "shops",
     "description": "Buckets of bricks, sets and a build-your-own bar.", "address": "42 Stud Ave",
     "image": "https://images.unsplash.com/photo-1779384027896-3c78d80e230b?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Hobby Bench", "cuisine": "Hobby Shop", "price": "$$", "rating": 4.6, "distance": 4.9, "category": "shops",
     "description": "Model kits, paints, RC cars and miniatures.", "address": "23 Craft Rd",
     "image": "https://images.unsplash.com/photo-1601067095185-b8b73ad7db10?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Two Wheels Cyclery", "cuisine": "Bicycle Shop", "price": "$$", "rating": 4.8, "distance": 3.0, "category": "shops", "sponsored": True,
     "description": "Road, gravel and city bikes plus expert tune-ups.", "address": "6 Pedal Way",
     "image": "https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Gilded Gem Jewelers", "cuisine": "Jewelry Store", "price": "$$$", "rating": 4.8, "distance": 2.7, "category": "shops",
     "description": "Fine jewelry, custom rings and estate pieces.", "address": "14 Carat Ct",
     "image": "https://images.unsplash.com/photo-1689560025810-4599bc195814?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "The Pawn Vault", "cuisine": "Pawn Shop", "price": "$$", "rating": 4.3, "distance": 7.2, "category": "shops",
     "description": "Instruments, tools, electronics and gold buys.", "address": "50 Ticket St",
     "image": "https://images.unsplash.com/photo-1622704776938-bed6cd156e04?crop=entropy&cs=srgb&fm=jpg&q=85"},

    # --- Fuel ---
    {"name": "QuickFill Station", "cuisine": "Gas Station", "price": "$", "rating": 4.4, "distance": 0.6, "category": "fuel", "sponsored": True,
     "description": "24/7 pumps, fresh coffee and a well-stocked mart.", "address": "2 Pump Row",
     "image": "https://images.unsplash.com/photo-1709536240401-58dff8e8d597?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Corner Fuel Co", "cuisine": "Gas Station", "price": "$", "rating": 4.2, "distance": 2.3, "category": "fuel",
     "description": "Regular, premium and air pumps with a car vacuum.", "address": "88 Octane Ave",
     "image": "https://images.unsplash.com/photo-1695561324569-5e47c76dc0a3?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Midnight Mart & Gas", "cuisine": "Gas Station", "price": "$", "rating": 4.3, "distance": 4.8, "category": "fuel",
     "description": "Late-night fill-ups, snacks and lottery.", "address": "12 Fuel Ln",
     "image": "https://images.unsplash.com/photo-1635627026254-b652e62d1d07?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "VoltPoint Charging", "cuisine": "EV Charging", "price": "$$", "rating": 4.7, "distance": 1.1, "category": "fuel", "sponsored": True,
     "description": "Fast DC chargers with a lounge and free wifi.", "address": "5 Current Ct",
     "image": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "GreenCharge Hub", "cuisine": "EV Charging", "price": "$$", "rating": 4.6, "distance": 3.5, "category": "fuel",
     "description": "Level 2 and fast chargers next to a coffee bar.", "address": "30 Watt Way",
     "image": "https://images.unsplash.com/photo-1593941707874-ef25b8b4a92b?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Highway Haven Truck Stop", "cuisine": "Truck Stop", "price": "$", "rating": 4.5, "distance": 8.4, "category": "fuel", "sponsored": True,
     "description": "Diesel lanes, showers, diner and overnight parking.", "address": "1 Interstate Rd",
     "image": "https://images.unsplash.com/photo-1783243858623-aa17e2e07779?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Big Rig Rest Stop", "cuisine": "Truck Stop", "price": "$", "rating": 4.3, "distance": 14.7, "category": "fuel",
     "description": "High-flow diesel, weigh station and 24hr diner.", "address": "77 Mile Marker",
     "image": "https://images.unsplash.com/photo-1602126719641-078917db06d1?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Diesel Depot", "cuisine": "Diesel", "price": "$", "rating": 4.4, "distance": 6.9, "category": "fuel",
     "description": "Dedicated diesel lanes and DEF at every pump.", "address": "40 Cetane St",
     "image": "https://images.unsplash.com/photo-1635627026254-b652e62d1d07?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Sparkle Touchless Wash", "cuisine": "Touchless Car Wash", "price": "$$", "rating": 4.6, "distance": 1.8, "category": "fuel", "sponsored": True,
     "description": "Brushless laser wash with spot-free rinse.", "address": "9 Shine Ave",
     "image": "https://images.unsplash.com/photo-1633014041037-f5446fb4ce99?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"name": "Sudsy's Car Wash", "cuisine": "Car Wash", "price": "$", "rating": 4.4, "distance": 3.2, "category": "fuel",
     "description": "Soft-cloth tunnel wash with free vacuums.", "address": "22 Bubble Blvd",
     "image": "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?crop=entropy&cs=srgb&fm=jpg&q=85"},
]


async def seed_db():
    count = await db.restaurants.count_documents({})
    if count == 0:
        docs = []
        for idx, item in enumerate(SEED):
            r = Restaurant(**item)
            r.open_now = (idx % 4 != 0)  # ~25% shown as closed for the Open-now filter
            doc = r.model_dump()
            doc['created_at'] = doc['created_at'].isoformat()
            docs.append(doc)
        await db.restaurants.insert_many(docs)
        logging.info(f"Seeded {len(docs)} restaurants")
    else:
        # Backfill any newly-added curated categories (e.g. shops, fuel) into an
        # already-seeded DB without duplicating existing spots.
        existing = set(await db.restaurants.distinct("name"))
        new_docs = []
        for idx, item in enumerate(SEED):
            if item["name"] in existing:
                continue
            r = Restaurant(**item)
            r.open_now = (idx % 4 != 0)
            doc = r.model_dump()
            doc['created_at'] = doc['created_at'].isoformat()
            new_docs.append(doc)
        if new_docs:
            await db.restaurants.insert_many(new_docs)
            logging.info(f"Backfilled {len(new_docs)} curated spots")
    # Seed the global "fates dealt" social-proof counter
    if await db.stats.count_documents({"key": "fates_dealt"}) == 0:
        await db.stats.insert_one({"key": "fates_dealt", "count": 1042})


def apply_filters(items, cuisines, prices, max_distance):
    result = items
    if cuisines:
        result = [r for r in result if r['cuisine'] in cuisines]
    if prices:
        result = [r for r in result if r['price'] in prices]
    if max_distance is not None:
        result = [r for r in result if r['distance'] <= max_distance]
    return result
